apiVersion: v1
kind: Secret
metadata:
  name: he-apikey-secret
  namespace: cert-manager
data:
  key: "he-ddns-key"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: email@mail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: example-issuer-account-key
    solvers:
    - dns01:
        webhook:
          groupName: dyn.dns.he.net
          solverName: acme-he-webhook
          config:
            apiKeySecretRef:
              name: he-apikey-secret
            email: mail@mail.com
      selector:
        dnsZones:
        - 'somedomain.com'
