---
# Source: acme-he-webhook/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acme-he-webhook
  namespace: "cert-manager"
  labels:
    app: acme-he-webhook
    chart: acme-he-webhook-0.1.0
    release: acme-he-webhook
    heritage: Helm
---
# Source: acme-he-webhook/templates/rbac.yaml
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acme-he-webhook:domain-solver
  labels:
    app: acme-he-webhook
    chart: acme-he-webhook-0.1.0
    release: acme-he-webhook
    heritage: Helm
rules:
  - apiGroups:
      - dyn.dns.he.net
    resources:
      - '*'
    verbs:
      - 'create'
  - apiGroups:
      - "flowcontrol.apiserver.k8s.io"
    resources:
      - 'prioritylevelconfigurations'
      - 'flowschemas'
    verbs:
      - 'list'
      - 'watch'
---
# Source: acme-he-webhook/templates/rbac.yaml
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acme-he-webhook:auth-delegator
  labels:
    app: acme-he-webhook
    chart: acme-he-webhook-0.1.0
    release: acme-he-webhook
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: acme-he-webhook
    namespace: "cert-manager"
---
# Source: acme-he-webhook/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acme-he-webhook:domain-solver
  labels:
    app: acme-he-webhook
    chart: acme-he-webhook-0.1.0
    release: acme-he-webhook
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acme-he-webhook:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: "cert-manager"
---
# Source: acme-he-webhook/templates/rbac.yaml
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: acme-he-webhook:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: acme-he-webhook
    chart: acme-he-webhook-0.1.0
    release: acme-he-webhook
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: acme-he-webhook
    namespace: "cert-manager"
---
# Source: acme-he-webhook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: acme-he-webhook
  namespace: "cert-manager"
  labels:
    app: acme-he-webhook
    chart: acme-he-webhook-0.1.0
    release: acme-he-webhook
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: acme-he-webhook
    release: acme-he-webhook
---
# Source: acme-he-webhook/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "cert-manager"
  name: acme-he-webhook
  labels:
    app: acme-he-webhook
    chart: acme-he-webhook-0.1.0
    release: acme-he-webhook
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme-he-webhook
      release: acme-he-webhook
  template:
    metadata:
      labels:
        app: acme-he-webhook
        release: acme-he-webhook
    spec:
      serviceAccountName: acme-he-webhook
      containers:
        - name: acme-he-webhook
          image: "quay.io/gattytto/acme-he-webhook:latest"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "dyn.dns.he.net"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
      volumes:
        - name: certs
          secret:
            secretName: acme-he-webhook-webhook-tls
---
# Source: acme-he-webhook/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.dyn.dns.he.net
  labels:
    app: acme-he-webhook
    chart: acme-he-webhook-0.1.0
    release: acme-he-webhook
    heritage: Helm
  annotations:
    cert-manager.io/inject-ca-from: "gattytto-code/acme-he-webhook-webhook-tls"
spec:
  group: dyn.dns.he.net
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: acme-he-webhook
    namespace: cert-manager
  version: v1alpha1
---
# Source: acme-he-webhook/templates/pki.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: acme-he-webhook-ca
  namespace: "cert-manager"
  labels:
    app: acme-he-webhook
    chart: acme-he-webhook-0.1.0
    release: acme-he-webhook
    heritage: Helm
spec:
  secretName: acme-he-webhook-ca
  duration: 43800h # 5y
  issuerRef:
    name: acme-he-webhook-selfsign
  commonName: "ca.acme-he-webhook.cert-manager"
  isCA: true
---
# Source: acme-he-webhook/templates/pki.yaml
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: acme-he-webhook-webhook-tls
  namespace: "cert-manager"
  labels:
    app: acme-he-webhook
    chart: acme-he-webhook-0.1.0
    release: acme-he-webhook
    heritage: Helm
spec:
  secretName: acme-he-webhook-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: acme-he-webhook-ca
  dnsNames:
  - acme-he-webhook
  - acme-he-webhook.gattytto-code
  - acme-he-webhook.gattytto-code.svc
---
# Source: acme-he-webhook/templates/pki.yaml
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: acme-he-webhook-selfsign
  namespace: "cert-manager"
  labels:
    app: acme-he-webhook
    chart: acme-he-webhook-0.1.0
    release: acme-he-webhook
    heritage: Helm
spec:
  selfSigned: {}
---
# Source: acme-he-webhook/templates/pki.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: acme-he-webhook-ca
  namespace: "cert-manager"
  labels:
    app: acme-he-webhook
    chart: acme-he-webhook-0.1.0
    release: acme-he-webhook
    heritage: Helm
spec:
  ca:
    secretName: acme-he-webhook-ca
