apiVersion: v1
kind: Secret
metadata:
  name: acme-he-test-tls
  namespace: cert-manager
  annotations:
    kubed.appscode.com/sync: ""
type: kubernetes.io/tls
data:
  ca.crt: ''
  tls.crt: ''
  tls.key: ''

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-he-test
  namespace: cert-manager
spec:
  # Secret names are always required.
  secretName: acme-he-test-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - lasmalvinassonargentinas
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: somedomain.com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  - somedomain.com
  issuerRef:
    name: letsencrypt-staging
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
